---
title: "App Globals Report"
output: pdf_document
params:
  globals: NULL
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Mietspiegel der Stadt Passau, gültig ab November 2024

## Bestimmung der ortsüblichen Vergleichsmiete für Wohnraum auf der Grundlage folgender Angaben:

### Wohnungsgröße
- Auswahl: `r params$globals$groesse$selection`
- Info Text: `r params$globals$groesse$info_text`
- Untere Spannengrenze (ug): `r params$globals$groesse$lo`
- Ortsübliche Vergleichsmiete (oue): `r params$globals$groesse$mid`
- Obere Spannengrenze (og): `r params$globals$groesse$hi`

---

### Wohnlage
- Ergebnis: `r params$globals$adresse$info_text`
- Basierend auf: `r params$globals$adresse$selection`


### Baujahr
- Ergebnis: `r params$globals$baujahr$info_text`
- Basierend auf: `r params$globals$baujahr$selection`

---

### Renovierung
- Ergebnis: `r params$globals$renovierung$info_text`
- Basierend auf: `r paste(params$globals$renovierung$selection, collapse = ", ")`

---

### Sanitär
- Ergebnis: `r params$globals$sanitaer$info_text`
- Basierend auf: `r paste(params$globals$sanitaer$selection, collapse = ", ")`

---

### Ausstattung
- Ergebnis: `r params$globals$ausstattung$info_text`
- Basierend auf: `r paste(params$globals$ausstattung$selection, collapse = ", ")`

---

### Gesamtfaktoren
- Aggregierter Faktor: `r params$globals$sum$factor`
- Info Text: `r params$globals$sum$info_text`

```
